### ISSUE TITLE
Add skip for nginx on initialise

### ISSUE THREAD

**Issue by tobiasraabe** [tobiasraabe/otree_virtual_machine_manager#113]
* oTree Virtual Machine Manager version:
* Python version:
* Operating System:

### Description

Rerunning initialise deletes the current nginx config.

**Comment by tobiasraabe** [comment]
Just to make sure. Is it correct that we need two nginx templates? Also, under the third bullet of first run (https://otree-virtual-machine-manager.readthedocs.io/en/latest/usage.html) the docs state that ``nginx_template`` resides in the home folder but it is located in /home/user/ovmm_sources. Can you confirm that? We should also mention the second template if it is needed.

**Comment by cataclysmic** [comment]
One is for the "default nginx config" controlling port 80 and 443.
The other one is for the user specific ports.
Both contain different options to some degree.
We could consider merging those...
